#CodeDeploy 설정파일
version: 0.0
os: linux
files:
  - source: /
    destination: /root/app/step2/zip/    #jar파일을 저장할 ec2 경로를 설정
    overwrite: yes
permissions: #codeDeploy에서 넘겨준 파일의 권한수준: ec2-user
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStart: #CodeDeploy가 ApplicationStart단계일때, ec2-user권한으로 deploy.sh파일을 실행
    - location: deploy.sh
      timeout: 60
      runas: ec2-user