spring:
  datasource:
    hikari:
#      jdbc-url: jdbc:h2:tcp://localhost/~/awsPractice
      username: sa
      password:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:/root/awsPractice
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
        show_sql: true
  profiles: #profile추가
    active: oauth
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
logging:
  level:
    org.org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true