spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/awsPractice
      username: sa
      password:
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
        show_sql: true
  profiles: #profile추가
    active: oauth
logging:
  level:
    org.org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace