spring:
#  datasource:
##    nohup java -cp h2-2.3.232.jar org.h2.tools.Console -tcp &
#
#
#    url: jdbc:h2:tcp://localhost/~/awsPractice
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: true
#  jpa:
#    hibernate:
#      ddl-auto: create
#
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
  profiles: #profile추가
    active: oauth, real
  config:
    import:
      #- optional:file:/root/app/application-real-db.properties
      #- optional:file:/root/app/application-oauth.properties
      - application-real.properties
      - application-real-db.properties
      - application-oauth.properties
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
logging:
  level:
    org.org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
#
#---
#spring:
#  config:
#    activate:
#      on-profile: real
#  jpa:
#    database-platform: org.hibernate.dialect.MariaDBDialect
#    hibernate:
#      ddl-auto: none
#  session:
#    store-type: jdbc
